### ISSUE TITLE
Train de Charlevoix

### ISSUE THREAD

**Issue by WoozySweazy** [RailFansCanada/RailFansMap#249]
**Describe the bug**
On the system map, the Train de Charlevoix is listed as a system but the route does not appear on the interactive map. I expect that this issue is due to the option to portray the route being turned off in the background. For example, Via Rail and RTC have the option to either portray or not different lines onto the interactive map while that option does not exist for the Train de Charlevoix.
![Interactive map](https://user-images.githubusercontent.com/113273303/209426047-cff93a97-ee11-48fb-a4f3-95a2c09726d5.png)

The device used to observe this problem is a Window's Laptop using google chrome.

**Comment by dellisd** [comment]
It's very hard to see, but there is a checkbox next to the Charlevoix section. It's easier to see with the light theme.
![image](https://user-images.githubusercontent.com/6743693/209451254-ae477a8b-402b-45fb-996b-0757c182e4ea.png)

This is definitely a design problem and it's one I want to fix. I already have an issue open to track it (#175) so I'll close this one.

**Comment by WoozySweazy** [comment]
Thank you for the update!
